### ISSUE TITLE
Window resize listener?

### ISSUE THREAD

**Issue by sashabeep** [kovart/sticksy#7]
Tried 
```js
$(window).on('load resize orientationchange', function () {
	if (window.matchMedia("(min-width: 768px)").matches) {
		var stickyEl = new Sticksy('.s-cont > .sticky');
		stickyEl.hardRefresh()
	}else{
		Sticksy.disableAll(); ///seems do not clean the markup
	}
});
```

But after that i see a LOT of sticksy hidden nodes and element mispositioned till the page reload.

How to refresh state after window resize and clear the markup when sticky functionality is not needed?

![Снимок экрана 2021-05-21 в 15 39 33](https://user-images.githubusercontent.com/5689796/119138838-fecb1380-ba4a-11eb-9124-706fe794554c.png)

**Comment by kovart** [comment]
Looks like you initialize Sticksy instance each time you match the media query.
```
if (window.matchMedia("(min-width: 768px)").matches) {
		var stickyEl = new Sticksy('.s-cont > .sticky');
```
You need to initialize sticky element once and then use the instance methods when you match the query.
Fixed version:
```
var stickyEl = new Sticksy('.s-cont > .sticky');
$(window).on('load resize orientationchange', function () {
	if (window.matchMedia("(min-width: 768px)").matches) {
		stickyEl.hardRefresh()
	} else{
		stickyEl.disable();
	}
});
```

**Comment by sashabeep** [comment]
@kovart Looks like once it inited it works without any listeners to window resize
